### ISSUE TITLE
Include ECMA 402 proposals

### ISSUE THREAD

**Issue by sffc** [tc39/tc39.github.io#108] opened 2019-03-04 18:42 UTC
It takes several additional clicks to find the page with the ECMA 402 proposals.  For most users, the existence of the subcommittee versus the main plenary is unimportant, and ECMA 402 proposals have to go through the same rigorous stage advancement process in TC39 as all other proposals.  I would like to see the Stage 3 ECMA 402 proposals added to the home page.  (Not a launch blocker)

**Comment by sffc** [comment] 2019-03-04 18:43
Also, a link on the bottom next to "See more proposals" that goes directly to the ECMA 402 list: something like "See more Intl proposals"

**Comment by codehag** [comment] 2019-03-09 19:57
Thanks for the suggestion. I don't think we will manage this for the MVP but we should keep it in mind for the next iteration.

**Comment by codehag** [comment] 2019-03-09 20:13
This is in fact, a duplicate of our very first issue: #1 

We will close this one, and continue to work on this issue there, as this is a broader topic.

**Closed as completed by codehag** 2019-03-09 20:13 UTC
Labels: content, design
