### ISSUE TITLE
Consider how to include published ES standards (not only drafts)

### ISSUE THREAD

**Issue by codehag** [tc39/tc39.github.io#296] opened 2022-08-23 08:05 UTC
We have some feedback from Istvan, our liason to Ecma:

"TC39.es" is a bit misleading:

Under "spec" at the top and under "standards" at the bottom of the website only the links to the next Draft ES is given, but nowhere to the now existing ES standards:
E.g. for ECMA-262:

https://www.ecma-international.org/publications-and-standards/standards/ecma-262/

This might be a link like "see published standards".

A suggestion from Patrick: 

Under the “Specs” tab, change the existing “ECMA-262, ECMASCript” and “ECMA-402, Intl API” to something like “Draft ECMA-262, ECMASCript” and “Draft ECMA-402, Intl API”. Then we could add a link to the published standards, something like “Published ECMA-262, ECMASCript” and “Published ECMA-402, Intl API”.

**Comment by DerekNonGeneric** [comment] 2022-08-23 11:20
> [&hellip;] to something like “Draft ECMA-262, ECMAScript” and “Draft ECMA-402, Intl API”.

Can we call them Working Drafts like C++? I think I saw that @ https://eel.is/c++draft/ in the past. 

> [&hellip;] the current working draft for C++23. It replaces [N4901](http://open-std.org/jtc1/sc22/wg21/docs/papers/2021/n4901.pdf).
> &mdash; https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/n4911.html

This seems like good prior art that may be worth considering since simply calling them drafts might come off as sounding more meaningless than they really are given the discussion in https://github.com/tc39/tc39.github.io/issues/285 about living standards and the like.

We probably want to distinguish from being confused with W3c Editor's Drafts[^1] since might be quite different (unsure).

[^1]: https://www.w3.org/standards/types#ED

**Comment by ljharb** [comment] 2022-08-23 14:22
I think calling the living standard a draft is something we should avoid doing - we *want* people to prefer the spec on github to the almost immediately obsolete snapshots on ecma’s website.

**Comment by codehag** [comment] 2022-08-24 08:43
My understanding here is that part of the reason for this request to do this is related to the renewal of the trademark name "ECMAScript". I am not too sure about the details here, maybe @ecmageneva can give more information?

**Comment by ecmageneva** [comment] 2022-08-24 17:19
Two things:
"Draft Standard" vs "Standards": This always reflects the formal status of a standard at any SDO. "Standard" is what has been formally approved, "Draft Standard" what is not yet approved, so it can be different from the formally approved "Standard".
On the Trademark renewal process of "ECMAScript" I have to confess that I am not up to date. Patrick Luthi knows the current details. He works with the Ecma Trademark lawyer. First of all this is by country by country (or region, like Europe). So, I am not sure what is the concrete status in what country / region. As far as I remember the 10 years renewal we had maybe 2-3 years ago was in the USA, which is never an easy one. There the "Moddable" implementation of "ECMAScript" on a logic card with the trademark text was very helpful...

**Comment by ecmageneva** [comment] 2022-09-30 09:19
Dear All,

we looked at the TC39.es web site again and found that there is still some confusion there:

Therefore my proposal is the following:

1) The Tc39.es website is still confusing because "Standards" - at the bottom of the tc39.es page - contains both approved standards  and current stage (not approved) draft standards. If that column is "standards" then it should only contain the list and links to formally by the Ecma GA approved TC39 Standards. It means that in practice on that column there would be changes only after the June Ecma GA meetings.

2) For current stage - not yet approved - TC39 draft standard it would be better to create on the top, or the bottom, or both a column "Draft Standards" with the links to the latest stage current draft standards. It means that these entries would be updated at any appropriate time when a new version of the draft is published.

3) For the "Active proposals" (under the top) I would merge that with the "State of Proposals". Maybe with a new title "Proposals" and subdivide that into two parts: "State of Proposals" and "Active Proposals". Here the "State of Proposals" would only change if there is a policy change. So, in practice seldom. The "Active Proposals" would change frequently whenever required.

**Comment by DerekNonGeneric** [comment] 2022-09-30 11:30
> The Tc39.es website is still confusing because "Standards" - at the bottom of the tc39.es page - contains both approved standards and current stage (not approved) draft standards.

I agree that mixing the two as we currently have does add to the confusion. These changes were introduced in https://github.com/tc39/tc39.github.io/pull/299. I must have been very busy, but I would have voiced my preference of the first HTMLizing those two specs as mentioned in the issue @annevk opened: https://github.com/tc39/tc39.github.io/issues/283. The fact that they currently only exist in their PDF form and are also the latest ECMA GA-approved versions gives me the impression that they wouldn't be "living standards" unless those chairs were inclined to adopt that model.

Ideally, we would like to be able to link all of them to the HTML version of their "living form" ("draft standard" as you say, but others seem to be indicating a preference for terminology like "living standard" closer in meaning to how WHATWG operates).

As far as linking to the previously-ECMA GA-approved specs (the "standards" that are published annually), I liked what Twitter did by having [a little privacy policy archive](https://twitter.com/en/privacy/previous) for outdated material, but that seems like it would require having additional pages for those (four in total).

**Comment by annevk** [comment] 2022-09-30 12:22
@ecmageneva could you clarify what you mean by confusion? I think for the majority of visitors to this website the current links under "Specs" is what they will be looking for and splitting them in a way you suggest would end up with more confusion and make the website harder to navigate.

**Comment by ljharb** [comment] 2022-09-30 14:03
@ecmageneva the draft standard is living - its updated any time a commit is merged - and that’s what most everyone is looking for, not formal approval.

**Comment by ecmageneva** [comment] 2022-10-01 11:54
The problem is that in the Ecma community the term "living standard" so far did not exist. So, if you use that in Ecma not defined terms (even if it is clear for you what it means), then some other people in the community will not understand it and will be confused (otherwise I would not get these messages via the Ecma Secretariat...). The terms "Draft standard" and "Standard" is what everybody in Ecma understands and uses. Of course a "draft standard" is "living" - if your understanding is too, that it still can change until formal approval. "Draft standard" is the term that is used in the Ecma standards community. It is the same as in many other SDOs, like ISO, so people know that. Furthermore "Standard" is the term when the standard has been approved (like ES2022). Only then the formal process is through, in case of TC39 the RF approval process, etc.... In the interest of the entire Ecma community it is better to use terms that everybody there understands and uses. That is all.....

**Comment by annevk** [comment] 2022-10-01 13:55
So maybe a simple fix here would be that in the footer we replace "Standards" with "Specs" to align the terminology with that used in the header. That would avoid the perceived conflict.

**Comment by ljharb** [comment] 2022-10-01 14:10
@ecmageneva it seems more important to me to use terms the JavaScript community understands, since that’s who the spec is made for.

**Comment by ecmageneva** [comment] 2022-10-04 18:28
1) ljharb: Can you explain to me, why the "JavaScript community" wants ONLY to know what the not yet approved "latest draft standard of ECMA-262 and ECMA-402" says, but not the actual latest approved version of the standard (i.e. at present ES2022)?
2) The "latest draft standard" (this is what you point at under "Specs") is certainly good for information, but since it still may change before it is formally approved (e.g. in ES2023), therefore one has to be very careful when implementing it. Does the Tc39.es mention that somewhere?
3) TC39 is also part of the "Ecma community" since 1996. So the standard is also a formal Ecma standard.

**Comment by ljharb** [comment] 2022-10-04 19:10
@ecmageneva because the JS community largely only cares about what's shipped in engines, and that happens long before the standard is officially approved (which is a good thing). Changes in or after stage 3 are just as unlikely/likely as changes after official approval, so approval has no bearing on that at all.

**Comment by ctcpip** [comment] 2023-12-20 19:53
the living spec is the one people care about; nobody is waiting for the official 2023, 2024, etc. editions to come out before taking action.  in some cases browsers and JS engines have already shipped features several months before the yearly doc is publised

**Closed as not planned by ctcpip** 2023-12-20 19:53 UTC
Labels: good first issue, content
